CREATE TABLE `board` (
  `BOARD_NO` int NOT NULL AUTO_INCREMENT,
  `BOARD_TYPE` varchar(10) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `TITLE` varchar(100) DEFAULT NULL,
  `CONTENTS` varchar(500) DEFAULT NULL,
  `USER_ID` varchar(30) DEFAULT NULL,
  `CREATED_TIME` datetime DEFAULT NULL,
  `UPDATED_TIME` datetime DEFAULT NULL,
  `LIKES` int DEFAULT NULL,
  `COUNTS` int DEFAULT NULL,
  PRIMARY KEY (`BOARD_NO`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb3;