CREATE TABLE `board` (
  `BOARD_NO` int NOT NULL AUTO_INCREMENT,
  `BOARD_TYPE` varchar(10) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `TITLE` varchar(100) DEFAULT NULL,
  `CONTENTS` varchar(500) DEFAULT NULL,
  `USER_ID` varchar(30) DEFAULT NULL,
  `CREATED_TIME` datetime DEFAULT now(),
  `UPDATED_TIME` datetime DEFAULT now(),
  `LIKES` int DEFAULT NULL,
  `COUNTS` int DEFAULT NULL,
  PRIMARY KEY (`BOARD_NO`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb3;


CREATE TABLE `user` (
  `USER_ID` varchar(50) NOT NULL COMMENT '아이디',
  `USER_PW` varchar(255) NOT NULL COMMENT '비밀번호',
  `USER_NAME` varchar(50) NOT NULL COMMENT '사용자명',
  `PHONE` varchar(20) DEFAULT NULL COMMENT '연락처',
  `EMAIL` varchar(100) DEFAULT NULL COMMENT '이메일',
  `CREATED_TIME` datetime DEFAULT now() COMMENT '등록일자',
  `UPDATE_TIME` datetime DEFAULT now() COMMENT '수정일자',
  PRIMARY KEY (`USER_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;